apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            command:
            - /bin/sh
            - -c
            - |
              num=$(shuf -i 0-10 -n 1)
              echo "sleep $num"
              sleep $num
              result=$(shuf -i 0-1 -n 1)
              echo "result $result"
              test $result -eq 0
          restartPolicy: OnFailure

