apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-job-notifier-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-job-notifier-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-job-notifier
subjects:
# NOTE: WRITE YOUR SERVICE ACCOUNT
- kind: ServiceAccount
  name: k8s-job-notifier-sa
  namespace: k8s-job-notifier-production
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-job-notifier
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "list", "watch"]

